### ISSUE TITLE
support 5.6

### ISSUE THREAD

**Issue by jinpavg** [Cycling74/RNBOMetasound#63]
looks like we may need some adjustments to build in 5.6

build errors:
```
11>RNBOTransport.cpp(581,76): Error C4430 : missing type specifier - int assumed. Note: C++ does not support default-int
11>RNBOTransport.cpp(581,76): Error C2143 : syntax error: missing ',' before '&'
11>RNBOTransport.cpp(589,26): Error C4430 : missing type specifier - int assumed. Note: C++ does not support default-int
11>RNBOTransport.cpp(590,36): Error C2143 : syntax error: missing ',' before '&'
11>RNBOTransport.cpp(583,59): Error C2065 : 'InParams': undeclared identifier
11>RNBOTransport.cpp(583,57): Error C2530 : 'InputCollection': references must be initialized
11>RNBOTransport.cpp(586,50): Error C2065 : 'InParams': undeclared identifier
11>RNBOTransport.cpp(586,60): Error C2065 : 'InParams': undeclared identifier
11>RNBOTransport.cpp(586,120): Error C2065 : 'OutErrors': undeclared identifier
11>RNBOTransport.cpp(595,21): Error C2065 : 'InputCollection': undeclared identifier
11>RNBOTransport.cpp(595,20): Error C2512 : 'Metasound::TDataReadReference<RNBOMetasound::FTransport>::TDataReadReference': no appropriate default constructor available
```

**Comment by x37v** [comment]
checkout `rnbo1.4.0-ue5.6`
